### ISSUE TITLE
Heroku build failing

### ISSUE THREAD

**Issue by ows-ali** [freeCodeCamp/boilerplate-project-headerparser#2]
I am trying to upload this project on Heroku but I am getting this error: npm is known not to run on Node.js v4.4.5 Is there any changes required?

![image](https://user-images.githubusercontent.com/16830711/47708363-b6ab3200-dc4f-11e8-886e-450ed6819725.png)

**Comment by ivanduka** [comment]
npm did not work well with such an old version of Node as 4.4.5
Change the node version to something like 8 and everything will work
